name: Reusable workflow example

on:
  workflow_call:
    inputs:
      var_a:
        required: true
        type: string
      var_b:
        required: true
        type: string
    secrets:
      token:
        required: false

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Print input vars
      id: printinputvars
      run: |
         echo "VAR-A: ${{ github.event.inputs.var_a }}"
         echo "VAR-B: ${{ github.event.inputs.var_b }}"
         echo "SECRET: ${{ github.event.secrets.token }}"
